feature: refresh token auto login
tiki/core-account-service pull request #257
Opened 2023-11-16 18:03 UTC by MiroBenicio

# Issues Addressed

Closes #243

2023-11-17 21:49 UTC, mike-audi requested changes

2023-11-17 21:49 UTC, mike-audi commented on src/main/resources/public/assets/js/refresh.js
> +    username,
username is not part of this, you don't need the OTP cookie at all.

2023-11-20 12:40 UTC, MiroBenicio commented on src/main/resources/public/assets/js/refresh.js
> +    username,
removed!

2023-11-20 18:05 UTC, mike-audi approved these changes

2023-11-20 18:05 UTC, merged